version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ExpensioDbPassword123
      POSTGRES_DB: expensio-db
    ports:
      - "5432:5432"


